version: "3.3"
services:
  frontend:
    restart: always
    build: .
    ports:
      - "80:80"
  mysql:
    image: "mysql:5.6"
    restart: always
    ports: 
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: fmi123
       MYSQL_DATABASE: books
  backend:
    restart: always
    build: ./src/backend
    ports:
      - "5000:5000"
volumes:
  db_data: {}
